=== Pollopiccante/InstallPragmarTest/tests/xml_parsing_example/note.xsd
<xs:schema xmlns:tns="urn:my_namespace" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="urn:my_namespace" elementFormDefault="qualified">
	<xs:complexType name="Node" />
	<xs:complexType name="ASTNode">
		<xs:complexContent>
			<xs:extension base="tns:Node">
				<xs:sequence />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="SomeTreeNode">
		<xs:complexContent>
			<xs:extension base="tns:ASTNode">
				<xs:sequence>
					<xs:element name="child1" minOccurs="0" maxOccurs="1" type="tns:SomeTreeNodeField" />
					<xs:element name="child2" minOccurs="0" maxOccurs="1" type="tns:SomeTreeNodeField" />
				</xs:sequence>
				<xs:attribute name="myname" type="xs:string" use="required" />
				<xs:attribute name="myflag" type="xs:boolean" use="required" />
				<xs:attribute name="mycounter" type="xs:int" use="optional" />
				<xs:attribute name="myslidervalue" type="xs:float" use="required" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="RequiredInnerNode">
		<xs:complexContent>
			<xs:extension base="tns:SomeTreeNode">
				<xs:sequence>
					<xs:element name="safe_child" minOccurs="1" maxOccurs="1" type="tns:SomeTreeNodeField" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="SomeTreeNodeField">
		<xs:choice>
			<xs:element name="RequiredInnerNode" type="tns:RequiredInnerNode" />
			<xs:element name="SomeTreeNode" type="tns:SomeTreeNode" />
		</xs:choice>
	</xs:complexType>
	<xs:complexType name="SomeTreeNodeFieldList">
		<xs:choice minOccurs="0" maxOccurs="unbounded">
			<xs:element name="RequiredInnerNode" type="tns:RequiredInnerNode" />
			<xs:element name="SomeTreeNode" type="tns:SomeTreeNode" />
		</xs:choice>
	</xs:complexType>
	<xs:element name="root">
		<xs:complexType>
			<xs:choice>
				<xs:element name="Node" type="tns:Node" />
				<xs:element name="ASTNode" type="tns:ASTNode" />
				<xs:element name="SomeTreeNode" type="tns:SomeTreeNode" />
				<xs:element name="RequiredInnerNode" type="tns:RequiredInnerNode" />
			</xs:choice>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Pollopiccante/InstallPragmarTest/tests/xml_parsing_example/note.xml
<?xml version="1.0" encoding="UTF-8"?>

<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="urn:my_namespace note.xsd"
      xmlns="urn:my_namespace">

    <SomeTreeNode myname="A" mycounter="1" myflag="true" myslidervalue="0.56">
        <child1>
            <RequiredInnerNode myname="B" mycounter="2" myslidervalue="0.7878" myflag="true">
                <child2>
                    <SomeTreeNode myname="C" mycounter="3" myflag="false" myslidervalue="0.9128"/>
                </child2>
                <safe_child>
                    <SomeTreeNode myname="D" mycounter="4" myflag="false" myslidervalue="2983748325.352352">

                    </SomeTreeNode>
                </safe_child>
            </RequiredInnerNode>
        </child1>
    </SomeTreeNode>
</root>
